server:
  error:
    include-message: always
  port: 8085
spring:
  application.name: Kafkaapp
  datasource:
    data: classpath:import_user_profile.sql
    driverClassName: org.h2.Driver
    platform: h2
    initialization-mode: always
    password:
    username: sa
    url: jdbc:h2:mem:kafkaapp
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc-swagger-ui:
  path: /swagger-ui.html
springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
  swagger-ui:
    tagsSorter: alpha
  writer-with-order-by-keys: true

api:
  version: 1.0.0-beta
  server:
    description: Local development
    url: http://localhost:8080

security:
  jwt:
    secret-key: c25e794ddd4539bc81573741a2f1e06e507645c6903570ddf9ccd040b2d6e8dc
    expiration-time: 3600000

management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
    web:
      exposure:
        include: health,info,beans,env,metrics
