[versions]
h2 = "2.3.232"

[libraries]
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }

[plugins]
springframework-boot = { id = "org.springframework.boot", version = "3.5.0" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }

